######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 17 12:18:35 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
