######################################################################
# Automatically generated by qmake (2.01a) Tue Apr 17 11:58:43 2018
######################################################################

TEMPLATE = app
TARGET = 
DEPENDPATH += .
INCLUDEPATH += .

# Input
SOURCES += simple.cpp
